from geneformer import EmbExtractor

# initiate EmbExtractor
embex = EmbExtractor(nproc=32, emb_label=['input_ids', 'AD_diagnosis', 'msex', 'age_death', 'batch', 'Major_Cell_Type'],
                     labels_to_plot=['Major_Cell_Type'],
                     token_dictionary_file='/path/to/token_dictionary.pkl',
                     max_ncells=1200000)

# extracts embedding from input data
# input data is tokenized rank value encodings generated by Geneformer tokenizer
embs = embex.extract_embs("/path/to/geneformer/model/",
                          "/path/to/PFC427_train_clean_anno_sample.dataset/",
                          "/path/to/main_folder",
                          "PFC427_train_sample_emb")

